#!/bin/ash
if [ -f /etc/tinc/.setup-complete ]; then
  nohup tinc-monitor > /dev/null &
  tincd -D -U nobody
else
  tinc-setup
  touch /etc/tinc/.setup-complete
  nohup tinc-monitor > /dev/null &
  tincd -D -U nobody
fi
